mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  redis:
    host: 116.205.187.238
    port: 6380
    timeout: 5000
    database: 0
    password: Password
    lettuce:
      shutdown-timeout:
cache:
  key:
    ArticleHeatCacheKey: ArticleHeatCache
