spring:
  datasource:
    url: jdbc:mysql://116.205.187.238:3306/new_blog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: Password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 10
      read-only: false
  application:
    name: newblog-blog
  redis:
    host: 116.205.187.238
    port: 6379
    timeout: 5000
    database: 0
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      key-prefix: CACHE_
      use-key-prefix: true
      # 允许空值缓存，解决缓存穿透
      cache-null-values: true

server:
  port: 8881
  servlet:
    context-path: /blog

oauth:
  grant_type: password
  client_id: newblog
  client_secret: userPassWd
  scope: all
  url: http://116.205.187.238:8880/api/auth/oauth/token
  check_url:  http://116.205.187.238:8880/api/auth/oauth/check_token


allowUrl: /index/**

blog:
  thread:
    coreSize: 20
    maxSize: 50
    keepAliveTime: 10

