server:
  port: 8884
  servlet:
    context-path: /three

# 邮箱发送配置
spring:
  application:
    name: newblog-three-server
  datasource:
    url: jdbc:mysql://116.205.187.238:3306/new_common?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: Password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 10
      read-only: false
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: 1537069101@qq.com
    password: ireixorvrquxbacd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  redis:
    port: 6379
    host: 116.205.187.238
  rabbitmq:
    host: 116.205.187.238
    username: root
    password: Password
    port: 5672

mq:
  config:
    exchange:
      route: route.direct
    queue:
      routing-key:
        email: emial_queue
        log: log_queue
