spring:
  datasource:
    url: jdbc:mysql://116.205.187.238:3306/new_user?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: Password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 10
      read-only: false
  application:
    name: newblog-user
  rabbitmq:
    port: 5672
    addresses: 116.205.187.238
    password: guest
    username: guest
server:
  port: 8885
  servlet:
    context-path: /user
#logging:
#  level:
#   root: debug
oauth:
  grant_type: password
  client_id: newblog
  client_secret: userPassWd
  scope: all
  url: http://116.205.187.238:8880/api/auth/oauth/token
  check_url:  http://116.205.187.238:8880/api/auth/oauth/check_token


allowUrl: /info/login,/comment/get,/info/register,/info/getUser/**,/comment/heat-list

mq:
  config:
    exchange:
      log: log.direct
    queue:
      routing-key:
        log: log_queue
