spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user_route
          uri: lb://newblog-user
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/$\{segment}
        - id: blog_route
          uri: lb://newblog-blog
          predicates:
            - Path=/api/blog/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/$\{segment}
        - id: auth_route
          uri: lb://newblog-auth
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/$\{segment}
        - id: three_route
          uri: lb://newblog-three-server
          predicates:
            - Path=/api/three/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/$\{segment}

  datasource:
    url: jdbc:mysql://localhost:3306/newblog_user?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: tl20010213
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: newblog-gateway

server:
  port: 8880
